-- =============================================================================
-- 07_crop_yields.sql — Rendements par culture × par région française
-- =============================================================================
-- Source : docs/02-architecture/03_CONTENT_DATA.md §6 (données Agreste/FranceAgriMer)
-- Les régions utilisées sont les anciennes régions administratives (pré-2016)
-- car les données agronomiques sont historiquement découpées ainsi.
-- Le mapping ancien→nouveau est fait côté applicatif.
-- Rendements en T/ha, ajustés pour le gameplay.
-- NULL = culture non pratiquée dans la région.
-- =============================================================================

-- Table de mapping des anciennes régions pour les rendements
-- (region_slug, crop_slug, yield_t_per_ha)

INSERT INTO crop_yield (region_slug, crop_slug, yield_t_per_ha) VALUES
-- ─── BLÉ ────────────────────────────────────────────────────────────────────
('alsace',              'ble', 7.0),
('aquitaine',           'ble', 5.7),
('auvergne',            'ble', 6.2),
('basse_normandie',     'ble', 8.1),
('bourgogne',           'ble', 6.1),
('bretagne',            'ble', 7.3),
('centre',              'ble', 6.8),
('champagne_ardenne',   'ble', 7.6),
('corse',               'ble', 3.4),
('franche_comte',       'ble', 6.0),
('haute_normandie',     'ble', 8.4),
('ile_de_france',       'ble', 7.7),
('languedoc_roussillon','ble', 4.8),
('limousin',            'ble', 5.2),
('lorraine',            'ble', 6.4),
('midi_pyrenees',       'ble', 5.6),
('nord_pas_de_calais',  'ble', 8.6),
('pays_de_loire',       'ble', 7.0),
('picardie',            'ble', 8.3),
('poitou_charentes',    'ble', 6.6),
('paca',                'ble', 4.0),
('rhone_alpes',         'ble', 6.0),

-- ─── ORGE ───────────────────────────────────────────────────────────────────
('alsace',              'orge', 6.0),
('aquitaine',           'orge', 5.6),
('auvergne',            'orge', 5.5),
('basse_normandie',     'orge', 6.9),
('bourgogne',           'orge', 5.8),
('bretagne',            'orge', 7.0),
('centre',              'orge', 6.6),
('champagne_ardenne',   'orge', 6.4),
('corse',               'orge', 3.0),
('franche_comte',       'orge', 5.8),
('haute_normandie',     'orge', 7.7),
('ile_de_france',       'orge', 7.1),
('languedoc_roussillon','orge', 4.6),
('limousin',            'orge', 5.2),
('lorraine',            'orge', 6.0),
('midi_pyrenees',       'orge', 5.1),
('nord_pas_de_calais',  'orge', 7.9),
('pays_de_loire',       'orge', 6.4),
('picardie',            'orge', 7.5),
('poitou_charentes',    'orge', 6.2),
('paca',                'orge', 3.9),
('rhone_alpes',         'orge', 5.6),

-- ─── ORGE DE PRINTEMPS ──────────────────────────────────────────────────────
('alsace',              'orge_printemps', 4.6),
('aquitaine',           'orge_printemps', 5.0),
('auvergne',            'orge_printemps', 4.5),
('basse_normandie',     'orge_printemps', 5.8),
('bourgogne',           'orge_printemps', 4.8),
('bretagne',            'orge_printemps', 6.5),
('centre',              'orge_printemps', 6.1),
('champagne_ardenne',   'orge_printemps', 6.7),
('corse',               'orge_printemps', 2.7),
('franche_comte',       'orge_printemps', 5.0),
('haute_normandie',     'orge_printemps', 7.3),
('ile_de_france',       'orge_printemps', 6.5),
('languedoc_roussillon','orge_printemps', 3.5),
('limousin',            'orge_printemps', 3.6),
('lorraine',            'orge_printemps', 5.5),
('midi_pyrenees',       'orge_printemps', 4.1),
('nord_pas_de_calais',  'orge_printemps', 8.4),
('pays_de_loire',       'orge_printemps', 5.3),
('picardie',            'orge_printemps', 7.2),
('poitou_charentes',    'orge_printemps', 5.7),
('paca',                'orge_printemps', 1.8),
('rhone_alpes',         'orge_printemps', 4.6),

-- ─── AVOINE ─────────────────────────────────────────────────────────────────
('alsace',              'avoine', 4.2),
('aquitaine',           'avoine', 4.3),
('auvergne',            'avoine', 3.5),
('basse_normandie',     'avoine', 5.9),
('bourgogne',           'avoine', 3.8),
('bretagne',            'avoine', 5.2),
('centre',              'avoine', 4.5),
('champagne_ardenne',   'avoine', 5.5),
('corse',               'avoine', 2.6),
('franche_comte',       'avoine', 3.9),
('haute_normandie',     'avoine', 6.3),
('ile_de_france',       'avoine', 5.9),
('languedoc_roussillon','avoine', 3.3),
('limousin',            'avoine', 3.7),
('lorraine',            'avoine', 3.9),
('midi_pyrenees',       'avoine', 3.3),
('nord_pas_de_calais',  'avoine', 6.3),
('pays_de_loire',       'avoine', 5.4),
('picardie',            'avoine', 6.5),
('poitou_charentes',    'avoine', 4.4),
('paca',                'avoine', 2.4),
('rhone_alpes',         'avoine', 3.6),

-- ─── TRITICALE ──────────────────────────────────────────────────────────────
('alsace',              'triticale', 6.2),
('aquitaine',           'triticale', 4.9),
('auvergne',            'triticale', 5.1),
('basse_normandie',     'triticale', 6.4),
('bourgogne',           'triticale', 5.0),
('bretagne',            'triticale', 6.4),
('centre',              'triticale', 5.3),
('champagne_ardenne',   'triticale', 6.5),
('corse',               'triticale', 3.5),
('franche_comte',       'triticale', 5.4),
('haute_normandie',     'triticale', 7.1),
('ile_de_france',       'triticale', 6.2),
('languedoc_roussillon','triticale', 3.9),
('limousin',            'triticale', 5.1),
('lorraine',            'triticale', 6.2),
('midi_pyrenees',       'triticale', 4.6),
('nord_pas_de_calais',  'triticale', 7.3),
('pays_de_loire',       'triticale', 5.8),
('picardie',            'triticale', 6.9),
('poitou_charentes',    'triticale', 5.3),
('paca',                'triticale', 4.0),
('rhone_alpes',         'triticale', 5.3),

-- ─── MAÏS GRAIN ─────────────────────────────────────────────────────────────
('alsace',              'mais_grain', 10.8),
('aquitaine',           'mais_grain', 9.0),
('auvergne',            'mais_grain', 9.1),
('basse_normandie',     'mais_grain', 8.6),
('bourgogne',           'mais_grain', 8.4),
('bretagne',            'mais_grain', 8.5),
('centre',              'mais_grain', 9.1),
('champagne_ardenne',   'mais_grain', 8.3),
('corse',               'mais_grain', 11.2),
('franche_comte',       'mais_grain', 8.4),
('haute_normandie',     'mais_grain', 9.0),
('ile_de_france',       'mais_grain', 9.2),
('languedoc_roussillon','mais_grain', 9.4),
('limousin',            'mais_grain', 6.9),
('lorraine',            'mais_grain', 7.5),
('midi_pyrenees',       'mais_grain', 9.7),
('nord_pas_de_calais',  'mais_grain', 9.4),
('pays_de_loire',       'mais_grain', 8.5),
('picardie',            'mais_grain', 8.8),
('poitou_charentes',    'mais_grain', 8.6),
('paca',                'mais_grain', 10.8),
('rhone_alpes',         'mais_grain', 9.4),

-- ─── MAÏS ENSILÉ ────────────────────────────────────────────────────────────
('alsace',              'mais_ensile', 13.1),
('aquitaine',           'mais_ensile', 13.2),
('auvergne',            'mais_ensile', 10.3),
('basse_normandie',     'mais_ensile', 13.6),
('bourgogne',           'mais_ensile', 9.8),
('bretagne',            'mais_ensile', 13.2),
('centre',              'mais_ensile', 12.4),
('champagne_ardenne',   'mais_ensile', 10.8),
('corse',               'mais_ensile', 10.0),
('franche_comte',       'mais_ensile', 11.0),
('haute_normandie',     'mais_ensile', 14.7),
('ile_de_france',       'mais_ensile', 10.9),
('languedoc_roussillon','mais_ensile', 8.6),
('limousin',            'mais_ensile', 11.7),
('lorraine',            'mais_ensile', 10.4),
('midi_pyrenees',       'mais_ensile', 11.6),
('nord_pas_de_calais',  'mais_ensile', 15.1),
('pays_de_loire',       'mais_ensile', 12.4),
('picardie',            'mais_ensile', 14.5),
('poitou_charentes',    'mais_ensile', 11.0),
('paca',                'mais_ensile', 9.5),
('rhone_alpes',         'mais_ensile', 10.6),

-- ─── COLZA ──────────────────────────────────────────────────────────────────
('alsace',              'colza', 3.7),
('aquitaine',           'colza', 2.7),
('auvergne',            'colza', 3.0),
('basse_normandie',     'colza', 3.7),
('bourgogne',           'colza', 3.0),
('bretagne',            'colza', 3.4),
('centre',              'colza', 3.3),
('champagne_ardenne',   'colza', 3.4),
('franche_comte',       'colza', 3.4),
('haute_normandie',     'colza', 3.9),
('ile_de_france',       'colza', 3.6),
('languedoc_roussillon','colza', 2.8),
('limousin',            'colza', 3.1),
('lorraine',            'colza', 3.0),
('midi_pyrenees',       'colza', 2.9),
('nord_pas_de_calais',  'colza', 3.9),
('pays_de_loire',       'colza', 3.7),
('picardie',            'colza', 3.8),
('poitou_charentes',    'colza', 3.3),
('paca',                'colza', 2.1),
('rhone_alpes',         'colza', 3.3),

-- ─── TOURNESOL ──────────────────────────────────────────────────────────────
('alsace',              'tournesol', 2.5),
('aquitaine',           'tournesol', 2.3),
('auvergne',            'tournesol', 2.5),
('basse_normandie',     'tournesol', 2.5),
('bourgogne',           'tournesol', 2.4),
('bretagne',            'tournesol', 2.5),
('centre',              'tournesol', 2.6),
('champagne_ardenne',   'tournesol', 3.5),
('corse',               'tournesol', 1.5),
('franche_comte',       'tournesol', 2.5),
('haute_normandie',     'tournesol', 2.8),
('ile_de_france',       'tournesol', 2.8),
('languedoc_roussillon','tournesol', 2.0),
('limousin',            'tournesol', 1.9),
('lorraine',            'tournesol', 2.8),
('midi_pyrenees',       'tournesol', 2.1),
('pays_de_loire',       'tournesol', 2.6),
('picardie',            'tournesol', 2.5),
('poitou_charentes',    'tournesol', 2.3),
('paca',                'tournesol', 1.9),
('rhone_alpes',         'tournesol', 2.4),

-- ─── BETTERAVE ──────────────────────────────────────────────────────────────
('alsace',              'betterave', 75),
('auvergne',            'betterave', 60),
('basse_normandie',     'betterave', 80),
('bourgogne',           'betterave', 70),
('centre',              'betterave', 82),
('champagne_ardenne',   'betterave', 76),
('haute_normandie',     'betterave', 90),
('ile_de_france',       'betterave', 75),
('lorraine',            'betterave', 60),
('nord_pas_de_calais',  'betterave', 90),
('picardie',            'betterave', 90),
('poitou_charentes',    'betterave', 75),

-- ─── POIS ───────────────────────────────────────────────────────────────────
('alsace',              'pois', 3.3),
('aquitaine',           'pois', 3.5),
('auvergne',            'pois', 2.9),
('basse_normandie',     'pois', 4.8),
('bourgogne',           'pois', 3.0),
('bretagne',            'pois', 4.2),
('centre',              'pois', 4.6),
('champagne_ardenne',   'pois', 4.6),
('corse',               'pois', 2.5),
('franche_comte',       'pois', 2.8),
('haute_normandie',     'pois', 5.0),
('ile_de_france',       'pois', 4.8),
('languedoc_roussillon','pois', 2.7),
('limousin',            'pois', 2.8),
('lorraine',            'pois', 4.1),
('midi_pyrenees',       'pois', 3.2),
('nord_pas_de_calais',  'pois', 5.3),
('pays_de_loire',       'pois', 3.8),
('picardie',            'pois', 5.2),
('poitou_charentes',    'pois', 4.3),
('paca',                'pois', 2.1),
('rhone_alpes',         'pois', 3.2),

-- ─── FÉVEROLE ───────────────────────────────────────────────────────────────
('alsace',              'feverole', 3.0),
('aquitaine',           'feverole', 2.3),
('auvergne',            'feverole', 2.5),
('basse_normandie',     'feverole', 4.3),
('bourgogne',           'feverole', 3.2),
('bretagne',            'feverole', 4.2),
('centre',              'feverole', 3.5),
('champagne_ardenne',   'feverole', 4.0),
('corse',               'feverole', 2.5),
('franche_comte',       'feverole', 2.9),
('haute_normandie',     'feverole', 5.0),
('ile_de_france',       'feverole', 4.0),
('languedoc_roussillon','feverole', 2.3),
('limousin',            'feverole', 3.1),
('lorraine',            'feverole', 3.2),
('midi_pyrenees',       'feverole', 2.0),
('nord_pas_de_calais',  'feverole', 4.6),
('pays_de_loire',       'feverole', 3.5),
('picardie',            'feverole', 4.3),
('poitou_charentes',    'feverole', 2.9),
('paca',                'feverole', 2.6),
('rhone_alpes',         'feverole', 2.0),

-- ─── SOJA ───────────────────────────────────────────────────────────────────
('alsace',              'soja', 3.4),
('aquitaine',           'soja', 2.6),
('auvergne',            'soja', 2.5),
('bourgogne',           'soja', 2.6),
('centre',              'soja', 2.2),
('champagne_ardenne',   'soja', 2.2),
('corse',               'soja', 1.3),
('franche_comte',       'soja', 2.5),
('ile_de_france',       'soja', 2.8),
('languedoc_roussillon','soja', 2.8),
('lorraine',            'soja', 2.3),
('midi_pyrenees',       'soja', 2.7),
('pays_de_loire',       'soja', 2.2),
('poitou_charentes',    'soja', 2.3),
('paca',                'soja', 2.6),
('rhone_alpes',         'soja', 3.1),

-- ─── LIN ────────────────────────────────────────────────────────────────────
('basse_normandie',     'lin', 3.5),
('champagne_ardenne',   'lin', 3.3),
('haute_normandie',     'lin', 3.6),
('ile_de_france',       'lin', 3.5),
('nord_pas_de_calais',  'lin', 3.7),
('picardie',            'lin', 3.4),

-- ─── POMME DE TERRE ─────────────────────────────────────────────────────────
('alsace',              'pomme_de_terre', 41.2),
('aquitaine',           'pomme_de_terre', 33.9),
('auvergne',            'pomme_de_terre', 29.7),
('basse_normandie',     'pomme_de_terre', 33.9),
('bourgogne',           'pomme_de_terre', 36.4),
('bretagne',            'pomme_de_terre', 24.6),
('centre',              'pomme_de_terre', 48.2),
('champagne_ardenne',   'pomme_de_terre', 50.5),
('corse',               'pomme_de_terre', 9.2),
('franche_comte',       'pomme_de_terre', 27.2),
('haute_normandie',     'pomme_de_terre', 45.2),
('ile_de_france',       'pomme_de_terre', 48.0),
('languedoc_roussillon','pomme_de_terre', 24.9),
('limousin',            'pomme_de_terre', 28.2),
('lorraine',            'pomme_de_terre', 38.1),
('midi_pyrenees',       'pomme_de_terre', 30.7),
('nord_pas_de_calais',  'pomme_de_terre', 44.9),
('pays_de_loire',       'pomme_de_terre', 30.2),
('picardie',            'pomme_de_terre', 44.5),
('poitou_charentes',    'pomme_de_terre', 26.0),
('paca',                'pomme_de_terre', 30.0),
('rhone_alpes',         'pomme_de_terre', 28.0),

-- ─── SORGHO ENSILÉ ──────────────────────────────────────────────────────────
('alsace',              'sorgho_ensile', 8.8),
('aquitaine',           'sorgho_ensile', 12.1),
('auvergne',            'sorgho_ensile', 11.0),
('bourgogne',           'sorgho_ensile', 9.3),
('centre',              'sorgho_ensile', 9.3),
('franche_comte',       'sorgho_ensile', 9.3),
('languedoc_roussillon','sorgho_ensile', 11.0),
('limousin',            'sorgho_ensile', 9.3),
('lorraine',            'sorgho_ensile', 8.8),
('midi_pyrenees',       'sorgho_ensile', 10.0),
('pays_de_loire',       'sorgho_ensile', 10.5),
('poitou_charentes',    'sorgho_ensile', 9.3),
('paca',                'sorgho_ensile', 11.0),
('rhone_alpes',         'sorgho_ensile', 11.0),

-- ─── LENTILLE ───────────────────────────────────────────────────────────────
('auvergne',            'lentille', 1.5),
('bourgogne',           'lentille', 2.5),
('centre',              'lentille', 2.5),
('champagne_ardenne',   'lentille', 3.1),
('languedoc_roussillon','lentille', 1.6),
('midi_pyrenees',       'lentille', 1.5),
('pays_de_loire',       'lentille', 1.9),
('poitou_charentes',    'lentille', 1.6),

-- ─── ÉPINARD ────────────────────────────────────────────────────────────────
('bretagne',            'epinard', 23),
('centre',              'epinard', 20),
('champagne_ardenne',   'epinard', 16),
('ile_de_france',       'epinard', 15),
('languedoc_roussillon','epinard', 15),
('midi_pyrenees',       'epinard', 12),
('nord_pas_de_calais',  'epinard', 23),
('pays_de_loire',       'epinard', 12),
('picardie',            'epinard', 22),
('paca',                'epinard', 21),
('rhone_alpes',         'epinard', 14),

-- ─── HARICOT VERT ───────────────────────────────────────────────────────────
('aquitaine',           'haricot_vert', 12),
('bourgogne',           'haricot_vert', 13),
('bretagne',            'haricot_vert', 13),
('centre',              'haricot_vert', 11),
('champagne_ardenne',   'haricot_vert', 11),
('franche_comte',       'haricot_vert', 14),
('ile_de_france',       'haricot_vert', 13),
('languedoc_roussillon','haricot_vert', 13),
('midi_pyrenees',       'haricot_vert', 11),
('nord_pas_de_calais',  'haricot_vert', 15),
('pays_de_loire',       'haricot_vert', 13),
('picardie',            'haricot_vert', 15),
('poitou_charentes',    'haricot_vert', 13),
('paca',                'haricot_vert', 12),
('rhone_alpes',         'haricot_vert', 11),

-- ─── TABAC ──────────────────────────────────────────────────────────────────
('alsace',              'tabac', 2.7),
('aquitaine',           'tabac', 2.8),
('auvergne',            'tabac', 2.6),
('bretagne',            'tabac', 3.0),
('centre',              'tabac', 2.7),
('champagne_ardenne',   'tabac', 2.7),
('franche_comte',       'tabac', 2.9),
('limousin',            'tabac', 2.6),
('midi_pyrenees',       'tabac', 2.6),
('nord_pas_de_calais',  'tabac', 2.3),
('pays_de_loire',       'tabac', 2.7),
('picardie',            'tabac', 2.3),
('poitou_charentes',    'tabac', 3.0),
('rhone_alpes',         'tabac', 2.9),

-- ─── AVOINE DE PRINTEMPS ────────────────────────────────────────────────────
('alsace',              'avoine_printemps', 4.0),
('aquitaine',           'avoine_printemps', 4.2),
('auvergne',            'avoine_printemps', 3.2),
('basse_normandie',     'avoine_printemps', 5.7),
('bourgogne',           'avoine_printemps', 3.6),
('bretagne',            'avoine_printemps', 5.1),
('centre',              'avoine_printemps', 4.4),
('champagne_ardenne',   'avoine_printemps', 5.2),
('corse',               'avoine_printemps', 2.6),
('franche_comte',       'avoine_printemps', 3.8),
('haute_normandie',     'avoine_printemps', 6.0),
('ile_de_france',       'avoine_printemps', 5.6),
('languedoc_roussillon','avoine_printemps', 3.2),
('limousin',            'avoine_printemps', 3.6),
('lorraine',            'avoine_printemps', 3.8),
('midi_pyrenees',       'avoine_printemps', 3.2),
('nord_pas_de_calais',  'avoine_printemps', 6.2),
('pays_de_loire',       'avoine_printemps', 5.3),
('picardie',            'avoine_printemps', 6.2),
('poitou_charentes',    'avoine_printemps', 4.2),
('paca',                'avoine_printemps', 2.4),
('rhone_alpes',         'avoine_printemps', 3.5);
